---
- name: Ensure a modules system group ({{ modules_sys_user }})
  become: yes
  register: group_created
  ansible.builtin.group:
    state: present
    system: true
    name: "{{ modules_sys_user }}"

- name: Info¦ created group?
  ansible.builtin.debug:
    msg: "{{ group_created }}"

- name: Ensure a modules system user ({{ modules_sys_user }})
  become: yes
  register: user_created
  ansible.builtin.user:
    state:       present
    system:      true
    create_home: true
    # password: "!"
    # shell: "/usr/sbin/nologin"
    shell:   "/bin/false"
    comment: "modules system user"
    home:    "/var/admin/modules"
    name:    "{{ modules_sys_user }}"
    group:   "{{ modules_sys_user }}"

- name: Info¦ created user?
  ansible.builtin.debug:
    msg: "{{ user_created }}"
